build:
    install:
        - apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-kor tesseract-ocr-eng poppler-utils libglib2.0-0
        - pip install --no-cache-dir -r requirements.txt
    copy:
        - .
run:
    command: uvicorn pdf2docx.main:app --host 0.0.0.0 --port 8000
    port: 8000
entrypoint: pdf2docx.main:app
