openapi: "3.0.1"
info:
    title: PDF to DOCX Converter
    version: "1.0.0"

paths:
    /tools/list:
        post:
            tags: ["tools"]
            operationId: listTools
            responses:
                "200":
                    description: OK
            security:
                - anonymous: []
    /tools/call:
        post:
            tags: ["tools"]
            operationId: callTool
            requestBody:
                required: true
            responses:
                "200":
                    description: OK

components:
    securitySchemes:
        anonymous:
            type: none
